
    
-- IDENTIFY CANDIDATES WHO HAVE THE SAME DATE OF BIRTH BUT DIFFERENT NAMES.

SELECT 
    [dob] AS [DATE OF BIRTH],
    COUNT([application_no]) AS [NUMBER OF CANDIDATES],
    STRING_AGG([name], ', ') AS [NAMES OF CANDIDATES]
FROM 
    [dbo].[candidates]
GROUP BY 
    [dob]
HAVING 
    COUNT(DISTINCT [name]) > 1;
