--- CALCULATE THE PERCENTAGE OF CANDIDATES WHO HAVE A HIGHSCHOOL_GPA BETWEEN 3.0 AND 3.5.


SELECT
    CAST(ROUND(COUNT(CASE WHEN [highschool_gpa] 
    BETWEEN 3.0 AND 3.5 THEN 1 ELSE NULL END) * 100.0 / COUNT(*), 2) 
    AS DECIMAL(5, 2)) AS Percentage
FROM
   [dbo].[candidates_marks]

