
-- CALCULATE THE TOTAL NUMBER OF CANDIDATES BORN IN EACH YEAR AND MONTH.

SELECT 
COUNT (*) AS [TOTAL NUMBER OF CONDIDATES],
YEAR([dob]) AS [YEAR OF BIRTH], 
MONTH([dob]) AS [MONTH OF BIRTH]
FROM [dbo].[candidates] 
GROUP BY  YEAR([dob]),  MONTH([dob])
ORDER BY [YEAR OF BIRTH] DESC, [MONTH OF BIRTH] DESC
